apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: utbetalinger
  namespace: okonomi
  labels:
    team: okonomi
spec:
  env:
  - name: CORS_ALLOWED_ORIGIN
    value: "https://okonomiportalen.intern.dev.nav.no"
  image: {{ image }}
  port: 7100
  liveness:
    path: /utbetalinger/internal/isAlive
    initialDelay: 10
  readiness:
    path: /utbetalinger/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /utbetalinger/internal/metrics
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://okonomiportalen.intern.dev.nav.no/utbetalinger"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
